/**
 * Helpers for generating the per-page Tailwind entry files at
 * src/styles/.build/<name>.css from each page's _shared imports.
 *
 * Shared between scripts/build-css.mjs (build-time generation + Tailwind
 * compile) and astro.config.mjs (Vite dev plugin that regenerates entries
 * when a page's frontmatter changes).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Per-page Tailwind targets. Each entry produces public/css/<name>.css and
 * gets its `_shared` @sources auto-injected from the page's frontmatter.
 */
export const PAGE_TARGETS = [
  { name: 'uae',                    input: 'src/styles/uae.css',                    page: 'src/pages/uae.astro' },
  { name: 'uaev2',                  input: 'src/styles/uaev2.css',                  page: 'src/pages/uaev2.astro' },
  { name: 'oman-e-invoicing',       input: 'src/styles/oman-e-invoicing.css',       page: 'src/pages/oman-e-invoicing.astro' },
  { name: 'global-mandate',         input: 'src/styles/global-mandate.css',         page: 'src/pages/global-mandate.astro' },
  { name: 'global-mandate-v2',      input: 'src/styles/global-mandate-v2.css',      page: 'src/pages/global-mandate-v2.astro' },
  { name: 'scale-and-security',     input: 'src/styles/scale-and-security.css',     page: 'src/pages/scale-and-security.astro' },
  { name: 'erp-connectivity',       input: 'src/styles/erp-connectivity.css',       page: 'src/pages/erp-connectivity.astro' },
  { name: 'clear-compliance-cloud', input: 'src/styles/clear-compliance-cloud.css', page: 'src/pages/clear-compliance-cloud.astro' },
  { name: 'recon-ai-agent',         input: 'src/styles/recon-ai-agent.css',         page: 'src/pages/recon-ai-agent.astro' },
  { name: 'germany-product',         input: 'src/styles/germany-product.css',         page: 'src/pages/germany-product.astro' },
  { name: 'test',                   input: 'src/styles/test.css',                   page: 'src/pages/test.astro' },
  { name: 'france-product',          input: 'src/styles/france-product.css',          page: 'src/pages/france-product.astro' },
];

const SHARED_IMPORT_RE = /import\s+[A-Z][A-Za-z0-9]*\s+from\s+['"]\.\.\/sections\/_shared\/([A-Za-z0-9_-]+)\.astro['"]/g;

/**
 * Parse a page astro file's frontmatter for `_shared` component imports.
 * Returns deduped component names (e.g. ['NavbarGlobalV2', 'Footer']).
 */
export function discoverSharedSources(pagePath, root) {
  const src = readFileSync(resolve(root, pagePath), 'utf8');
  const parts = src.split('---');
  const frontmatter = parts.length > 2 ? parts[1] : '';
  const names = new Set();
  SHARED_IMPORT_RE.lastIndex = 0;
  let m;
  while ((m = SHARED_IMPORT_RE.exec(frontmatter)) !== null) names.add(m[1]);
  return Array.from(names);
}

/**
 * Write src/styles/.build/<name>.css for a page target.
 * Generated file `@imports` the original entry and appends `@source`
 * directives for each `_shared` import the page declares. `../../sections/`
 * has two `..`s because the generated file sits one level deeper than the
 * original entry (`src/styles/.build/` vs `src/styles/`).
 *
 * Returns { entryPath, sources, changed } where `changed` indicates whether
 * the file content differed from what was already on disk — useful for
 * skipping no-op writes during dev-server file watching.
 */
export function writeGeneratedEntry(target, root) {
  const names = discoverSharedSources(target.page, root);
  const buildDir = resolve(root, 'src/styles/.build');
  mkdirSync(buildDir, { recursive: true });
  const lines = [
    `/* AUTO-GENERATED by scripts/build-css.mjs. Do not edit. */`,
    `@import '../${target.input.split('/').pop()}';`,
    ...names.map((n) => `@source '../../sections/_shared/${n}.astro';`),
    '',
  ];
  const out = resolve(buildDir, `${target.name}.css`);
  const next = lines.join('\n');
  let prev = '';
  try { prev = readFileSync(out, 'utf8'); } catch { /* first run */ }
  const changed = next !== prev;
  if (changed) writeFileSync(out, next, 'utf8');
  return { entryPath: out, sources: names, changed };
}
